---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: podinfo-deploy-webapp
  namespace: wego-system
spec:
  interval: 1m0s
  path: ./deploy/webapp
  prune: true
  sourceRef:
    kind: GitRepository
    name: podinfo
  validation: client

